trigger:
- main

stages:

- stage: SCA_Dependencies
  displayName: "SCA Dependencies Analysis"
  jobs:
    - job: SCA
      displayName: "Run SCA with Safety"
      steps:
        - template: sca/sca-safety.yml

- stage: Build
  displayName: "Build Stage"
  dependsOn: SCA_Dependencies
  jobs:
    - job: BuildJob
      displayName: "Build Python Project"
      steps:
        - template: build/build.yml


- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
    - job: TestJob
      displayName: "Run Tests"
      steps:
        - template: test/test.yml