trigger:
- main

stages:

- stage: SCA_Dependencies
  displayName: "SCA Dependencies Analysis"
  jobs:
    - job: SCA
      displayName: "Run SCA with Safety"
      steps:

        - task: AdvancedSecurity-Codeql-Init@1
          inputs:
            languages: "python"
            enableAutomaticCodeQLInstall: true

        - task: AdvancedSecurity-Dependency-Scanning@1

        - task: AdvancedSecurity-Codeql-Analyze@1

        - script: |
            pip install -r requirements.txt
          displayName: 'Install dependencies'

        - script: |
            pip install safety
            safety check -r requirements.txt --policy-file=safety-policy.json --save-html=safety-report.html
          displayName: 'Run SCA with Safety'

        - task: publishhtmlreport@1
          inputs:
            htmlType: 'genericHTML'
            htmlPath: '$(Build.SourcesDirectory)/safety-report.html'


# - stage: Build
#   displayName: "Build Stage"
#   dependsOn: SCA_Dependencies
#   jobs:
#     - job: BuildJob
#       displayName: "Build Python Project"
#       steps:
#         - task: UsePythonVersion@0
#           inputs:
#             versionSpec: '3.x'
#             addToPath: true

#         - script: |
#             python -m pip install --upgrade pip
#             pip install -r requirements.txt
#           displayName: 'Install dependencies'

#         - script: |
#             echo "Building the project"
#           displayName: 'Run Build'


# - stage: Test
#   displayName: "Test Stage"
#   dependsOn: Build
#   jobs:
#     - job: TestJob
#       displayName: "Run Tests"
#       steps:
#         - task: UsePythonVersion@0
#           inputs:
#             versionSpec: '3.x'
#             addToPath: true

#         - script: |
#             python -m pip install --upgrade pip
#             pip install -r requirements.txt
#           displayName: 'Install dependencies'

#         - script: |
#             echo "Running tests"
#             pytest
#           displayName: 'Run Tests with pytest'

#         - task: PublishTestResults@2
#           inputs:
#             testResultsFiles: '**/test-*.xml'
#             testRunTitle: 'Python Tests'
#           displayName: 'Publish Test Results'